from __future__ import annotations

from collections.abc import Mapping
from typing import Any

class ThemeLoader:
    def __init__(self) -> None: ...

class StylesheetGenerator:
    def __init__(
        self, theme_data: Mapping[str, Any], advanced_mode: bool = ...
    ) -> None: ...
    def generate_qss(self) -> str: ...
